spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_test
    username: test
    password: test

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

slack:
  api:
    url: http://localhost