spring:
  application:
    name: notification-service
  profiles:
    active: prod

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

---
# 로컬 / 테스트 환경 (Config Server 안 띄우고 로컬 설정으로만 돌림)
spring:
  config:
    activate:
      on-profile: local, test
    import: "" # Config Server 접속 x

---
# 운영/배포 환경 (prod, dev 등 -> Fail-Fast 적용)
spring:
  config:
    activate:
      on-profile: prod, dev
    import: "configserver:" # Config Server 접속 실패 시 앱 다운 (Fail-Fast)
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server