spring:
  application:
    name: notification-service
  profiles:
    active: local

  cloud:
    #config:
    #  discovery:
    #    enabled: true
    #    service-id: config-server
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 3000
            logger-level: basic
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

message:
  exchange: baekma.exchange # Producer만 적용
  queue:
    delivery: delivery.queue
    hub: hub.queue
    notification: notification.queue
    order: order.queue

---
# 로컬 / 테스트 환경 (Config Server 안 띄우고 로컬 설정으로만 돌림)
spring:
  config:
    activate:
      on-profile: local, test

---
# 운영/배포 환경 (prod, dev 등 -> Fail-Fast 적용)
spring:
  config:
    activate:
      on-profile: prod, dev
    import: "configserver:http://logistics-config-server:18081" # Config Server 접속 실패 시 앱 다운 (Fail-Fast)