spring:
  application:
    name: notification-service
  profiles:
    active: local
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 3000
            logger-level: basic
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

message:
  exchange: baekma.exchange # Producer만 적용
  queue:
    delivery: delivery.queue
    hub: hub.queue
    notification: notification.queue
    order: order.queue